version: '3.8'

volumes:
  pg_demo: {}

services:
  java_db:
    container_name: java_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - ./pg_script:/docker-entrypoint-initdb.d
      - pg_demo:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  java_app:
    container_name: java_app
    image: java_app:latest
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - java_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java_db:5432/postgres
      - JAVA_OPTS -"Xmx512m"